on:
  pull_request: {}
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

permissions:
  contents: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kotlin-version:
          - '2.2.20'
          - '2.3.0'
          - '2.4.10'

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 21

      - uses: gradle/actions/setup-gradle@v5
      - run: ./gradlew clean build --continue -PkotlinVersion=${{ matrix.kotlin-version }}

      - uses: mikepenz/action-junit-report@v6
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
